spring:
  application:
    name: products-microservice
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: "*"